default: &default
  host: localhost
  user: postgres
  password: postgres
  adapter: postgres

development:
  <<: *default
  db: {{cookiecutter.project_slug}}_dev

test:
  <<: *default
  db: {{cookiecutter.project_slug}}_test

production:
  <<: *default
  db: {{cookiecutter.project_slug}}_prod